x_speed = 0; y_speed = 0;
move_speed = MOVE_SPEED; jump_force = JUMP_FORCE;
on_ground = false; facing = 1;
energy_segments = MAX_ENERGY_SEGMENTS;
energy_segments_max = MAX_ENERGY_SEGMENTS;
state = player_state_idle;
has_flight = true; has_extended_flight = false;
has_water_glide = false; has_wind_dash = false;
can_interact = false; interact_target = noone;
sprite_index = spr_player_idle; image_speed = 1;
