enum E_PLAYER_STATE { IDLE, WALK, JUMP, FALL, FLY, GLIDE, INTERACT, PUZZLE }
enum E_REALM { SKY, FOREST, FLOATING_ISLES, OCEAN, FLOWER_FIELD, RUINS, COUNT }
enum E_ABILITY { BASIC_FLIGHT, EXTENDED_FLIGHT_1, EXTENDED_FLIGHT_2, EXTENDED_FLIGHT_3, EXTENDED_FLIGHT_4, WATER_GLIDE, WIND_DASH, NONE }
enum E_CREATURE_STATE { IDLE, WANDER, APPROACH, RETREAT, INTERACT }
enum E_TRANSITION { NONE, FADE_OUT, FADE_IN }
