#macro MAX_ENERGY_SEGMENTS  4
#macro ENERGY_REGEN_RATE    0.02
#macro FLY_THRUST_FORCE    -18.0
#macro GRAVITY              0.8
#macro MOVE_SPEED           8.0
#macro JUMP_FORCE          -16.0
#macro GLIDE_GRAVITY        0.25
#macro GLIDE_TERMINAL       3.0
#macro GLIDE_H_MULTIPLIER   1.5
#macro OCEAN_GRAVITY        0.3
#macro CAMERA_LERP_SPEED    0.08
#macro VIEW_W               1920
#macro VIEW_H               1080
#macro TILE_SIZE            16
#macro SAVE_FILE            "olim_save.json"
#macro TRANS_SPEED           0.017
